name: Build Installers

on:
  release:
    types: [published]

jobs:
  build-installers:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: mac
            artifact: scholarly-publisher-mac.dmg
          - os: ubuntu-latest
            platform: linux
            artifact: scholarly-publisher-linux.AppImage
          - os: windows-latest
            platform: win
            artifact: scholarly-publisher-win.exe

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Electron
      run: |
        cd electron
        npm ci
        cd ..
        
    - name: Build application
      run: npm run build
      
    - name: Create app icons
      run: |
        mkdir -p electron/assets
        cat > electron/assets/icon.svg << 'EOF'
        <svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" style="stop-color:#3B82F6;stop-opacity:1" />
              <stop offset="100%" style="stop-color:#1D4ED8;stop-opacity:1" />
            </linearGradient>
          </defs>
          <rect width="512" height="512" rx="80" fill="url(#grad)"/>
          <g transform="translate(128, 128) scale(0.5)">
            <path d="M 50 200 L 200 50 L 150 100 L 250 150 L 200 200 L 150 150 L 200 200 L 150 250 L 100 200 Z" 
                  fill="white" stroke="white" stroke-width="2"/>
            <line x1="150" y1="100" x2="200" y2="200" stroke="rgba(255,255,255,0.3)" stroke-width="3"/>
          </g>
        </svg>
        EOF
        
    - name: Convert icons (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install imagemagick
        convert electron/assets/icon.svg -resize 512x512 electron/assets/icon.png
        convert electron/assets/icon.svg -resize 256x256 electron/assets/icon.ico
        convert electron/assets/icon.svg -resize 512x512 electron/assets/icon.icns
        
    - name: Convert icons (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        convert electron/assets/icon.svg -resize 512x512 electron/assets/icon.png
        convert electron/assets/icon.svg -resize 256x256 electron/assets/icon.ico
        convert electron/assets/icon.svg -resize 512x512 electron/assets/icon.icns
        
    - name: Convert icons (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install imagemagick
        magick electron/assets/icon.svg -resize 512x512 electron/assets/icon.png
        magick electron/assets/icon.svg -resize 256x256 electron/assets/icon.ico
        magick electron/assets/icon.svg -resize 512x512 electron/assets/icon.icns
        
    - name: Build installer
      run: |
        cd electron
        npm run dist:${{ matrix.platform }}
        cd ..
        
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: electron/dist/
        
    - name: Create Release Assets
      if: matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: electron/dist/*
        tag_name: ${{ github.ref }}
        name: Scholarly Publisher v${{ github.ref_name }}
        body: |
          # Scholarly Publisher Desktop App
          
          ## 📦 Installers
          
          Download the installer for your platform:
          
          - **macOS**: `.dmg` file (drag to Applications)
          - **Windows**: `.exe` installer
          - **Linux**: `.AppImage` file
          
          ## 🚀 Features
          
          - 📄 Paper submission and management
          - 👥 User management with roles
          - 📊 Analytics dashboard
          - 🔍 Advanced search and filtering
          - 📱 Responsive design
          
          ## 💡 Installation
          
          1. Download the installer for your platform
          2. Run the installer
          3. Launch the app from your Applications/Programs menu
          
          ## 🔧 System Requirements
          
          - macOS 10.14+ / Windows 10+ / Linux (Ubuntu 18.04+)
          - 4GB RAM minimum
          - 500MB free disk space
          
          ## 🆘 Support
          
          If you encounter any issues, please:
          1. Check the [GitHub Issues](https://github.com/saman-rahbar/easy_publisher-/issues)
          2. Create a new issue with details about your problem
          
          ## 📝 License
          
          MIT License - see [LICENSE](https://github.com/saman-rahbar/easy_publisher-/blob/main/LICENSE) file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 